blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Community Support
    url: https://discord.gg/pZvWDF32jw
    about: Join our Discord community server to ask questions, chat, or get setup support.
