name: Build

on:
  workflow_call:
    inputs:
      release:
        description: 'Is this a release build?'
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

    - name: Set up JDK
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287
      with:
        distribution: 'temurin'
        java-version: 26

    - name: Cache Gradle Files
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.properties', '**/*.accesswidener', 'versions/versions.json') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      env:
        BUILD_ID: ${{ github.run_number }}
        BUILD_RELEASE: ${{ inputs.release }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: build-artifacts
        path: versions/*/build/libs/

    - name: Collect Mod Jars
      run: |
        shopt -s extglob
        mkdir mod-jars
        for jar in versions/*/build/libs/!(*-@(dev|sources|shadow)).jar; do
            cp -p "$jar" mod-jars/
        done
        ls -l mod-jars

    - name: Upload Mod Jars
      uses: actions/upload-artifact@v7
      with:
        name: mod-jars
        path: mod-jars/*.jar
