name: Release

run-name: ${{ github.event_name == 'workflow_dispatch' && format('Manual release for {0}', inputs.target_release_tag) || '' }}

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: The tag of the release you want to append the artifact to
        type: string
        required: true

jobs:
  matrix_prepare:
    uses: ./.github/workflows/matrix_prepare.yaml

  validate_release:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get github release information
        uses: cardinalby/git-get-release-action@1.2.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.target_release_tag }}

  build:
    needs: validate_release
    if: ${{ always() && !failure() && !cancelled() }} # Ensures build runs even if validate_release is skipped on auto-releases
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      release: true

  release:
    needs:
      - matrix_prepare
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix: ${{ fromJson(needs.matrix_prepare.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v7

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts
          path: build-artifacts

      - name: Get Github Release Information
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: get_release
        uses: cardinalby/git-get-release-action@1.2.6
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.inputs.target_release_tag }}

      - name: Generate Publish Related Information
        id: release_info
        run: |
          if [ "$GITHUB_EVENT_NAME" = "release" ]; then
              echo "tag_name=" >> $GITHUB_OUTPUT
          else
              echo "tag_name=${{ github.event.inputs.target_release_tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Read Common Properties
        id: properties_g
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          all: true

      - name: Read Version-Specific Properties
        id: properties_v
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: ${{ format('versions/{0}/gradle.properties', matrix.subproject) }}
          all: true

      - name: Prepare File Information
        id: file_info
        run: |
          shopt -s extglob
          FILE_PATHS=($(ls build-artifacts/${{ matrix.subproject }}/build/libs/!(*-@(dev|sources|shadow)).jar))

          if (( ${#FILE_PATHS[@]} != 1 )); then
              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
              exit 1
          fi

          FILE_PATH=${FILE_PATHS[0]}
          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
          echo "name=$(basename $FILE_PATH)" >> $GITHUB_OUTPUT
          echo "hash=$(sha256sum $FILE_PATH | awk '{ print $1 }')" >> $GITHUB_OUTPUT

      - name: Prepare Changelog
        uses: actions/github-script@v9
        id: changelog
        with:
          script: return process.env.CHANGELOG
          result-encoding: string
        env:
          CHANGELOG: |-
            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}

            -------

            Build Information

            - File name: `${{ steps.file_info.outputs.name }}`
            - SHA-256: `${{ steps.file_info.outputs.hash }}`
            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Publish Mods to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          MODRINTH_PROJECT_ID: ysmYXPgd  # https://modrinth.com/mod/shelf
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          github-tag: ${{ steps.release_info.outputs.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          files: ${{ steps.file_info.outputs.path }}

          name: ${{ format('{0} v{1} for mc{2}', steps.properties_g.outputs.mod_name, steps.properties_g.outputs.mod_version, steps.properties_v.outputs.minecraft_version) }}
          version: ${{ format('v{1}-mc{0}', steps.properties_v.outputs.minecraft_version, steps.properties_g.outputs.mod_version) }}
          version-type: release

          loaders: fabric
          game-versions: ${{ steps.properties_v.outputs.game_versions }}
          game-version-filter: any
          dependencies: |-
            modmenu(optional)

          github-changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
          modrinth-changelog: ${{ steps.changelog.outputs.result }}

          retry-attempts: 3
          retry-delay: 10000
