name: Update Modrinth Description

on:
  push:
    branches: [main]
    paths:
      - 'README.md'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: 3.14

      - name: Install Dependencies
        run: pip install requests

      - name: Update Modrinth Description
        env:
          MODRINTH_PROJECT_ID: ysmYXPgd  # https://modrinth.com/mod/shelf
          MODRINTH_API_TOKEN: ${{ secrets.MODRINTH_API_TOKEN }}
        run: python .github/workflows/scripts/update_modrinth_description.py
